# Generated by Django 5.1.4 on 2025-01-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0003_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='opnion',
            new_name='opinion',
        ),
    ]
